config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clients
  resources :employees
  resources :reserves
  get 'welcome/homepage'
  get 'welcome/acc'
  get 'welcome/gal'
  get 'welcome/loc'
  get 'welcome/act'
  get 'welcome/promo'
  get 'welcome/dine'
  get 'welcome/nav'


  root 'welcome#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/reserve.rb
class Reserve < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Reservation was successfully Made.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :email, :tel, :start, :end, :rooms, :adults, :message, :employee_id)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name)
    end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  before_action :set_reserf, only: [:show, :edit, :update, :destroy]

  # GET /reserves
  # GET /reserves.json
  def index
    @reserves = Reserve.all
  end

  # GET /reserves/1
  # GET /reserves/1.json
  def show
  end

  # GET /reserves/new
  def new
    @reserf = Reserve.new
  end

  # GET /reserves/1/edit
  def edit
  end

  # POST /reserves
  # POST /reserves.json
  def create
    @reserf = Reserve.new(reserf_params)

    respond_to do |format|
      if @reserf.save
        format.html { redirect_to @reserf, notice: 'Reserve was successfully created.' }
        format.json { render :show, status: :created, location: @reserf }
      else
        format.html { render :new }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reserves/1
  # PATCH/PUT /reserves/1.json
  def update
    respond_to do |format|
      if @reserf.update(reserf_params)
        format.html { redirect_to @reserf, notice: 'Reserve was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserf }
      else
        format.html { render :edit }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reserves/1
  # DELETE /reserves/1.json
  def destroy
    @reserf.destroy
    respond_to do |format|
      format.html { redirect_to reserves_url, notice: 'Reserve was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserf
      @reserf = Reserve.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserf_params
      params.require(:reserf).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end

  def acc
  end

   def gal
  end

  def loc
  end

  def act
  end

  def promo
  end

  def dine
  end

  def nav
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_form.html.erb
<div class="form-group">
    <br/><br/><br/><br/>
  </div>

<%= form_for(@client, html: { multipart: true }) do |f| %>
  <% if @client.errors.any? %>
   

      <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h4>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="container">
    <div class="row">
    <div class="col-lg-6 col-sm-12">

   <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :tel %><br>
    <%= f.text_field :tel, class: "form-control" %>
  </div>



 <div class="form-group">
    <%= f.label :Arrival  %><br>
    <%= f.date_select :start, class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.label :Departure  %><br>
    <%= f.date_select :end, class: "form-control" %>
  </div>
  </div>
   
   <div class="col-lg-6 col-sm-12">
  <div class="form-group">
    <%= f.label :Children_Below_5 %><br>
    <%= f.number_field :rooms, class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.label :Adults %><br>
    <%= f.number_field :adults, class: "form-control" %>
  </div>
   

   <div class="control-group">
    <%= f.label :Rooms, class: 'control-label' %><br>
    <%= collection_select( :client, :employee_id, Employee.all, :id, :name, {}, { :multiple => false } )  %>
  </div>
   </br>

  <div class="form-group">
    <%= f.label :Other_Additional_Facilities_If_Required %><br>
    <%= f.text_area :message, class: "form-control" %>
  </div>
   <div class="form-group">
     <%= f.submit :value => "Submit", class: "btn btn-primary" %>
  </div>
  
  </div></div></div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Creative - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/creative.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/welcome/homepage" style="color: #F0A700">
                 <!--New Legacy-->
                 <%= link_to image_tag("logo.jpg") %>

                  </a>
                
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                                    <li>
                <a class="page-scroll" href="/welcome/homepage" style="color: black">Home</a>
                </li>

                    <li>
                        <a class="page-scroll" href="/welcome/acc" style="color: black">Accomodation</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/act" style="color: black">Activities</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/clients/new" style="color: black">Reservations</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/dine" style="color: black">Bar and Dining</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/loc" style="color: black">Location</a>
                    </li>
                    <li>
                       <a class="page-scroll" href="/welcome/gal" style="color: black">Gallery/News</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/promo" style="color: black">Promotions</a>
                    </li>
                    
                    <li>
                        <a class="page-scroll" href="#contact" style="color: black">Contact</a>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

<div class="container">
  <h2 class="center">Reservations</h2>



  <div class="row" >
    <% @clients.each do |client| %>
      
        <p>Name: <%= client.name %></p>
        <p>Email: <%= client.email %></p>
        <p>Tel: <%= client.tel %></p>
        <p>Arrival Date: <%= client.start %></p>
        <p>Departure Date: <%= client.end %></p>
        <p>Number Of Rooms: <%= client.rooms %></p>
        <p>Number Of Adults: <%= client.adults %></p>
        <p>Other Details: <%= client.message %></p>
        <p>Room Type: <%= client.employee.name %></p>
        <p><% link_to 'Show', client %></p>
        <p><% link_to 'Edit', edit_client_path(client) %></p>
        <p><%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <br><br>
     
    <% end %>
  </div>
</div>

<br><br>

<% link_to '', new_client_path %>


<section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>+256 (0) 785 803 728  </p><br/>
                    <p>+256 (0) 750 036 096  </p><br/>
                    <p>+256 (0) 772 883 233  </p><br/>
                    <p>+256 (0) 701 844 226  </p><br/>
                    
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:admin@theriftvalleygamelodge.com">admin@theriftvalleygamelodge.com</a></p><br/>
                    <p>Copyright © Rift Valley Game Lodge 2017 </p><br/>
                    
                    <p>
                    <a href="https://www.facebook.com/thervglUG" target="_blank" title="Facebook"><img src="https://dl.dropboxusercontent.com/s/dekq2ekp2fu5wvr/if_Facebook_1288098.png" alt="Facebook"/></a>
                    <p><br/>
                    <p>Designed by :<a href="http://theglobalbusinessdevelopers.com/" target="_blank">Global Business Developers</a></p>


                </div>
            </div>
        </div>
    </section>


    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/creative.min.js"></script>

</body>

</html>

app/views/clients/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Creative - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/creative.min.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/welcome/homepage" style="color: #F0A700">
                 <!--New Legacy-->
                 <%= link_to image_tag("logo.jpg") %>

                  </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                <li>
                <a class="page-scroll" href="/welcome/homepage" style="color: black">Home</a>
                </li>

                    <li>
                        <a class="page-scroll" href="/welcome/acc" style="color: black">Accomodation</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/act" style="color: black">Activities</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/clients/new" style="color: black">Reservations</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/dine" style="color: black">Bar and Dining</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/loc" style="color: black">Location</a>
                    </li>
                    <li>
                       <a class="page-scroll" href="/welcome/gal" style="color: black">Gallery/News</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/welcome/promo" style="color: black">Promotions</a>
                    </li>
                    
                    <li>
                        <a class="page-scroll" href="#contact" style="color: black">Contact</a>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

 
</br>
                     </br>
                      </br>


<p id="notice"><%= notice %></p>
<div class="container">
    <div class="row">
    <div class="col-lg-6 col-sm-12">

<p>
  <strong>Name:</strong>
  <% @client.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @client.tel %>
</p>

<p>
  <strong>Arrival Date:</strong>
  <%= @client.start %>
</p>

<p>
  <strong>Departure Date:</strong>
  <%= @client.end %>
</p>
</div>
   
   <div class="col-lg-6 col-sm-12">
<p>
  <strong>Rooms:</strong>
  <%= @client.rooms %>
</p>

<p>
  <strong>Adults:</strong>
  <%= @client.adults %>
</p>

<p>
  <strong>Other Details:</strong>
  <%= @client.message %>
</p>
<p>
  <strong>Room Type:</strong>
  <%= @client.employee.name %>
</p>
</div>

<% link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', new_client_path %>

<section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>+256 (0) 785 803 728  </p><br/>
                    <p>+256 (0) 750 036 096  </p><br/>
                    <p>+256 (0) 772 883 233  </p><br/>
                    <p>+256 (0) 701 844 226  </p><br/>
                    
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:admin@theriftvalleygamelodge.com">admin@theriftvalleygamelodge.com</a></p><br/>
                    <p>Copyright © Rift Valley Game Lodge 2017 </p><br/>
                    
                    <p>
                    <a href="https://www.facebook.com/thervglUG" target="_blank" title="Facebook"><img src="https://dl.dropboxusercontent.com/s/dekq2ekp2fu5wvr/if_Facebook_1288098.png" alt="Facebook"/></a>
                    <p><br/>
                    <p>Designed by :<a href="http://theglobalbusinessdevelopers.com/" target="_blank">Global Business Developers</a></p>


                </div>
            </div>
        </div>
    </section>


    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/creative.min.js"></script>

</body>

</html>

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :employee_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Riftvalley</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/reserves/_form.html.erb
<%= form_with(model: reserf, local: true) do |form| %>
  <% if reserf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reserf.errors.count, "error") %> prohibited this reserf from being saved:</h2>

      <ul>
      <% reserf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :reserf_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reserves/edit.html.erb
<h1>Editing Reserf</h1>

<%= render 'form', reserf: @reserf %>

<%= link_to 'Show', @reserf %> |
<%= link_to 'Back', reserves_path %>

app/views/reserves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reserves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reserves.each do |reserf| %>
      <tr>
        <td><%= reserf.name %></td>
        <td><%= link_to 'Show', reserf %></td>
        <td><%= link_to 'Edit', edit_reserf_path(reserf) %></td>
        <td><%= link_to 'Destroy', reserf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reserf', new_reserf_path %>

app/views/reserves/new.html.erb
<h1>New Reserf</h1>

<%= render 'form', reserf: @reserf %>

<%= link_to 'Back', reserves_path %>

app/views/reserves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reserf.name %>
</p>

<%= link_to 'Edit', edit_reserf_path(@reserf) %> |
<%= link_to 'Back', reserves_path %>